### PR TITLE
Feat: added video details page

### PR DESCRIPTION
**Pull request by vinc3nati**
- added video details page
- lazy loader

image

### CODE REVIEW

**Review by Rohanmond — APPROVED** [review]
Learned lazy loading ...Folder structure looks cool

**Review by ravikumar1002 — APPROVED** [review]
nice folder structure
good to merge

**Review by Aman-Jain1996 — APPROVED** [review]
Nice work with lazy loading , PR good to merge

**Review by shrey27 — APPROVED** [review]
Great job using lazy loader
UI looks clean and very aesthetic
PR is good to merge

**Pull request merged**
